---
dist: bionic
language: java
jdk: openjdk11
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
before_cache: # https://docs.travis-ci.com/user/languages/java/#Caching
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script: ./gradlew check fatJar
